my_app_rubrique:
    resource: "@MyAppRubriqueBundle/Resources/config/routing.yml"
    prefix:   /

my_app_esprit:
    resource: "@MyAppEspritBundle/Resources/config/routing.yml"
    prefix:   /
# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

