my_app_esprit_homepage:
    pattern:  / 
    defaults: { _controller: MyAppEspritBundle:Default:index }
my_app_esprit_menu:
    pattern:  /menu 
    defaults: { _controller: MyAppEspritBundle:Menu:send }
    